### ISSUE TITLE
Add hold items

### ISSUE THREAD

**Issue by rorylombardi** [rorylombardi/tradingpost#1]
Mostly just need a text listing of items and their in-game sprites.

**Comment by broman** [comment]
What format would you need the in-game sprites to be in? Would just a link be fine?

**Comment by rorylombardi** [comment]
It's a little complicated, unfortunately! Bulbapedia has a list of them and their sprites: https://bulbapedia.bulbagarden.net/wiki/List_of_items_by_index_number_(Generation_VIII)

However! Not all of them are hold items, and some of them are just garbage data (e.g. "★Aql7235").

What would be required are:
 * A full set of sprites, like those for species in `/static/species` (I can probably take care of that).
 * All item index numbers that are valid hold items.
 * All English names by index number.

**Comment by rorylombardi** [comment]
Actually, this is now done.
