### ISSUE TITLE
Poster-restricted search prefills unrestricted query

### ISSUE THREAD

**Issue by jwisser** [rorylombardi/tradingpost#26]
## Steps to Reproduce
1. Create first listing.
2. Check "My listings". See first listing. (So far, so good.)
3. Create second listing.
4. Check "My listings". See only first listing. (This is where the wheels came off.)
5. Hard-refresh. Sign out and back in. Still only see first listing.

## Additional Notes
Listings in question are 899 and 914, created approximately seven minutes apart. Please let me know if I can provide other useful info here!

**Comment by rorylombardi** [comment]
The behavior is a little confusing! We currently prefill the search from your last search, even if you're just looking for all of your listings! We'll make the listings page ignore the prefill.
